## logging
logging:
  config: # log configuration file
  path: /Users/twer/tmp
  level:
#    org.springframework: DEBUG

## web server
server:
  port: 8080
  # address:
  # sessionTimeout:

## database
spring.datasource:
  url: jdbc:postgresql://localhost/temple
  username: twer
  password: 123
  driverClassName: org.postgresql.Driver

## application properties
name: shenzhang
